### PR TITLE
Add Portuguese translation.

### PR DESCRIPTION
**Pull request by ericonr**
Hey there!

I'd prefer to show this to a few people before getting it into ly, so I marked it as WIP. I will change it as soon as I have feedback!

### CODE REVIEW

**Comment by laggarcia** [comment]
I would do the following modifications:

path -> caminho
inicializar -> iniciar
login -> conectar

Token and buffer do have equivalent words in portuguese, but I would say they are not used in this context.

**Comment by ericonr** [comment]
I think these are sound modifications! Thanks :)

Will add them to the branch when I get home.

**Comment by ericonr** [comment]
@laggarcia 
I just fixed them! Thanks again c:

**Comment by ericonr** [comment]
Removed WIP flag, can be merged.

**Comment by cylgom** [comment]
thanks!

**Pull request merged**
