### PR TITLE
Minor fixes to spelling and filenames.

### PR DESCRIPTION
**Pull request by NamedKitten**

### CODE REVIEW

**Comment by cylgom** [comment]
I don't like capital letters in my filenames, but thank you for fixing the typo in the readme :)

**Comment by NamedKitten** [comment]
https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html
Makefile is the convention that is most followed for a reason but alright.

**Comment by oxodao** [comment]
I +1 the capital letter for this

**Comment by cylgom** [comment]
:'(

**Pull request merged**
