### PR TITLE
Added Wayland sessions support.

### PR DESCRIPTION
**Pull request by NokiDev**
Hi, I have forked your project, in order to be able to load my wayland session using sway.

So I made few changes to your code, and it seems to works correctly. 

wsetup.sh have been taken from SDDM repository around [there](https://github.com/sddm/sddm/blob/f749f1d65165de7ce7b9ae073b19f057b205ab35/data/scripts/wayland-session)

Hoping you'll have time to review the change.

PS : Do you have some tips for debugging ?

### CODE REVIEW

**Comment by NokiDev** [comment]
@cylgom Please can you review.

**Comment by cylgom** [comment]
Hi,
first thank you for your contribution, I read it quickly when you submitted it but have been very busy since then. Everything looks good to me, but I'd like to test it, since I now have another device on which I can (in theory) install wayland. If you know other people who can confirm it works this is fine for me as well, but I'd really like at least one other person to test it :)

**Comment by sclem** [comment]
I was able to test this today and it works

**Comment by oxodao** [comment]
Any updates ?

**Comment by NokiDev** [comment]
I have an issue with the actual PR, I don't know if it occurs with Xsession too. 
When exiting sway, I'm not able to logs again using ly.

Actually I can't debug ly when running. So again if someone has some tips. 
I'll try to fix that ASAP.

**Comment by roel0** [comment]
> I have an issue with the actual PR, I don't know if it occurs with Xsession too.
> When exiting sway, I'm not able to logs again using ly.
> 
> Actually I can't debug ly when running. So again if someone has some tips.
> I'll try to fix that ASAP.

This is caused by XDG_RUNTIME_DIR not being set in the second PAM session. This also occurs when using an other window manager like i3. Except i3 doesn't care about XDG_RUNTIME_DIR, while sway does.

This has nothing to do with your pull request, and implies that the PAM sessions are not perfectly handled, but I don't seem to be able to find the exact issue.

Your PR works perfect for me btw.

**Comment by NokiDev** [comment]
Huuum, it's certainly that ! Thanks for pointing at. You'd saved me some time :)

@cylgom Are you ready to merge the change ? Or does it need a little more testing, or feedbacks ?

**Comment by cylgom** [comment]
Good news: a bug has been fixed in Sway so I can now test Wayland stuff on my computer. Good job @NokiDev it works flawlessly. The logout bug is entirely my fault, I guess I have some homework to do (btw thanks for the details @roel0).

**Comment by robertgzr** [comment]
are you going to tag a new release with the wayland stuff included?

**Comment by cylgom** [comment]
Done, actually re-wrote the entire thing :)

**Pull request merged**
